# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.ImageField(upload_to='user_images/'),
        ),
    ]
